# Generated by Django 5.1.1 on 2024-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_rename_image_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(),
        ),
    ]
